name: MADEK/madek/media-service
windows:
  2:
    name: server-run
    command: |
      export DB_NAME=madek
      export PGDATABASE=madek
      # export LOGGING_CONFIG_FILE=log-conf-dev.edn
      # we need do wait for the front-end to build the assets before we start up
      sleep 30
      ./bin/clj-run server run
  3:
    name: front-repl-run
    command: |
      ./bin/cljs-watch-app
  5:
    name: psql
    command: |
      psql -d madek

  6:
    name: datalayer
    command: |
      cd datalayer

  7:
    name: test
    command: |
      bundle

  8:
    name: inspector
    command: |
      ./bin/inspector-run

